# Generated by Django 4.2 on 2023-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2000)),
                ('short_url', models.CharField(max_length=200)),
            ],
        ),
    ]
